### ISSUE TITLE
mvn command not working with archetypeID 4.0.0.0

### ISSUE THREAD

**Issue by ppazos** [cucumber/cucumber-archetype#4]
```
$ mvn archetype:generate                                  \
>   -DarchetypeGroupId=io.cucumber                        \
>   -DarchetypeArtifactId=cucumber-archetype              \
>   -DarchetypeVersion=4.0.0.0                            \
> 
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] >>> maven-archetype-plugin:3.0.1:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO] 
[INFO] <<< maven-archetype-plugin:3.0.1:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO] 
[INFO] 
[INFO] --- maven-archetype-plugin:3.0.1:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Interactive mode
[INFO] Archetype repository not defined. Using the one from [io.cucumber:cucumber-archetype:2.3.1] found in catalog remote
[WARNING] The POM for io.cucumber:cucumber-archetype:jar:4.0.0.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.464 s
[INFO] Finished at: 2018-12-22T19:31:32-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.0.1:generate (default-cli) on project standalone-pom: The desired archetype does not exist (io.cucumber:cucumber-archetype:4.0.0.0) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```

**Comment by NerdishShah** [comment]
> ```
> $ mvn archetype:generate                                  \
> >   -DarchetypeGroupId=io.cucumber                        \
> >   -DarchetypeArtifactId=cucumber-archetype              \
> >   -DarchetypeVersion=4.0.0.0                            \
> > 
> [INFO] Scanning for projects...
> [INFO] 
> [INFO] ------------------< org.apache.maven:standalone-pom >-------------------
> [INFO] Building Maven Stub Project (No POM) 1
> [INFO] --------------------------------[ pom ]---------------------------------
> [INFO] 
> [INFO] >>> maven-archetype-plugin:3.0.1:generate (default-cli) > generate-sources @ standalone-pom >>>
> [INFO] 
> [INFO] <<< maven-archetype-plugin:3.0.1:generate (default-cli) < generate-sources @ standalone-pom <<<
> [INFO] 
> [INFO] 
> [INFO] --- maven-archetype-plugin:3.0.1:generate (default-cli) @ standalone-pom ---
> [INFO] Generating project in Interactive mode
> [INFO] Archetype repository not defined. Using the one from [io.cucumber:cucumber-archetype:2.3.1] found in catalog remote
> [WARNING] The POM for io.cucumber:cucumber-archetype:jar:4.0.0.0 is missing, no dependency information available
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  10.464 s
> [INFO] Finished at: 2018-12-22T19:31:32-03:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.0.1:generate (default-cli) on project standalone-pom: The desired archetype does not exist (io.cucumber:cucumber-archetype:4.0.0.0) -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> ```

Looks like they have not pushed this to maven central yet

**Comment by yash3x** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.0.1:generate (default-cli) on project standalone-pom: The desired archetype does not exist (io.cucumber:cucumber-archetype:4.0.0.0) -> [Help 1]

**Comment by mpkorstanje** [comment]
Looks like 4.0.0.0 was never released. 4.2.6.0 is available now

 https://search.maven.org/search?q=g:io.cucumber%20AND%20a:cucumber-archetype
